//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TugasSE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.ListDeliveries = new HashSet<ListDelivery>();
        }
    
        public string Username { get; set; }
        public int ApartementId { get; set; }
        public int RoomNumber { get; set; }
        public string Password { get; set; }
        public int RoleId { get; set; }
    
        public virtual Apartement Apartement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListDelivery> ListDeliveries { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
